"use client";

import type { CSSProperties, ReactNode } from "react";
import { IconRefresh, IconWarn } from "./icons";

/* ============================== identity ================================= */

/** The Infyield mark: an ascending yield curve with a mint terminal point,
 * drawn on a glass tile so it reads at any size. */
/**
 * The Infyield mark: the four-point sparkle, on the glass tile.
 *
 * This is deliberately the SAME glyph as the app icon (`infyield-icon.svg`) and
 * the favicon, both generated by scripts/build-icon.sh — so the Dock tile, the
 * browser tab and the nav all read as one identity. The sparkle geometry matches
 * `IconSparkle` (icons.tsx) too, so the brand mark and the in-app star icons are
 * the same shape rather than two lookalikes.
 *
 * `glow` adds the soft halo the larger surfaces carry; at nav size it is noise.
 */
export function Mark({ size = 28, glow = false, className = "" }: { size?: number; glow?: boolean; className?: string }) {
  const inner = Math.round(size * 0.62);
  const gradId = `infyield-mark-${glow ? "glow" : "flat"}`;
  return (
    <span
      className={`sheen relative grid shrink-0 place-items-center rounded-[26%] border border-[var(--border-2)] bg-[linear-gradient(160deg,rgba(255,255,255,0.16),rgba(255,255,255,0.03))] shadow-[0_10px_24px_-14px_rgba(0,0,0,0.95)] ${className}`}
      style={{ width: size, height: size }}
    >
      <svg width={inner} height={inner} viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <defs>
          <linearGradient id={gradId} x1="4" y1="20" x2="20" y2="4" gradientUnits="userSpaceOnUse">
            <stop stopColor="#46c8e8" />
            <stop offset="0.55" stopColor="#3ad2b6" />
            <stop offset="1" stopColor="#35e0a1" />
          </linearGradient>
        </defs>
        {glow && <path d={SPARKLE} fill={`url(#${gradId})`} opacity="0.5" filter="blur(3px)" />}
        <path d={SPARKLE} fill={`url(#${gradId})`} />
      </svg>
    </span>
  );
}

/** Four-point sparkle: tips on the axes, sides pulled toward the centre — the
 * same control-point ratio (19% of the radius) as the app icon, so the arms
 * survive being scaled down. */
const SPARKLE = "M12 2.6 Q13.1 10.9 21.4 12 Q13.1 13.1 12 21.4 Q10.9 13.1 2.6 12 Q10.9 10.9 12 2.6 Z";

export function Wordmark({ size = 28, label = "Infyield", className = "" }: { size?: number; label?: string; className?: string }) {
  return (
    <span className={`flex items-center gap-2.5 ${className}`}>
      <Mark size={size} />
      <span className="text-[15px] font-semibold tracking-[-0.02em] text-[var(--text-1)]">{label}</span>
    </span>
  );
}

/* ============================== structure ================================ */

export function SectionHeading({
  eyebrow,
  title,
  hint,
  action,
  tight = false,
}: {
  eyebrow?: string;
  title: string;
  hint?: string;
  action?: ReactNode;
  tight?: boolean;
}) {
  return (
    <div className={`mb-5 flex items-end justify-between gap-6 ${tight ? "mt-0" : ""}`}>
      <div className="min-w-0">
        {eyebrow && <div className="eyebrow mb-2">{eyebrow}</div>}
        <h2 className="t-h2">{title}</h2>
        {hint && <p className="t-meta mt-1.5 max-w-xl">{hint}</p>}
      </div>
      {action && <div className="flex shrink-0 items-center gap-2">{action}</div>}
    </div>
  );
}

export function Hairline({ className = "" }: { className?: string }) {
  return <div className={`hairline ${className}`} />;
}

/* ================================ stats ================================= */

export function Stat({
  label,
  value,
  hint,
  tone = "neutral",
  loading = false,
}: {
  label: string;
  value: string;
  hint?: string;
  tone?: "neutral" | "mint" | "amber" | "danger";
  loading?: boolean;
}) {
  const color =
    tone === "mint" ? "text-[var(--mint)]" : tone === "amber" ? "text-[var(--amber)]" : tone === "danger" ? "text-[#ff9b9b]" : "text-[var(--text-1)]";
  return (
    <div className="glass card-hover tile">
      <div className="eyebrow">{label}</div>
      {loading ? (
        <div className="skeleton mt-3 h-7 w-24" />
      ) : (
        <div className={`num mt-2 text-[26px] font-semibold leading-none ${color}`}>{value}</div>
      )}
      {hint && <div className="t-micro mt-2">{hint}</div>}
    </div>
  );
}

/* ============================== feedback ================================ */

export function Notice({
  tone = "info",
  title,
  children,
  action,
}: {
  tone?: "info" | "warn" | "success" | "danger";
  title?: string;
  children?: ReactNode;
  action?: ReactNode;
}) {
  const map = {
    info: "border-[var(--border-2)] bg-[rgba(255,255,255,0.035)]",
    warn: "border-[rgba(240,179,74,0.28)] bg-[rgba(240,179,74,0.08)]",
    success: "border-[rgba(53,224,161,0.3)] bg-[rgba(53,224,161,0.08)]",
    danger: "border-[rgba(255,110,110,0.28)] bg-[rgba(255,110,110,0.07)]",
  } as const;
  const dot = tone === "warn" ? "bg-[var(--amber)]" : tone === "success" ? "bg-[var(--mint)]" : tone === "danger" ? "bg-[#ff8080]" : "bg-[var(--text-3)]";
  return (
    // `flex-wrap` plus a min-width on the text is what keeps the action from
    // squeezing the copy into a one-word-per-line column in a narrow window: when
    // the text cannot hold its minimum, the action wraps onto its own row instead
    // of eating the remaining width. The action is `shrink-0` because a button
    // that shrinks to fit is worse than a button on the next line.
    <div className={`sheen flex flex-wrap items-start gap-x-3 gap-y-2.5 rounded-[var(--r-md)] border px-4 py-3 ${map[tone]}`}>
      <span className={`mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
      <div className="min-w-[13rem] flex-1">
        {title && <div className="text-[13.5px] font-medium text-[var(--text-1)]">{title}</div>}
        {children && <div className="t-meta mt-0.5 leading-relaxed">{children}</div>}
      </div>
      {action && <div className="ml-auto flex shrink-0 flex-wrap items-center gap-2">{action}</div>}
    </div>
  );
}

export function EmptyState({
  icon,
  eyebrow,
  title,
  body,
  action,
  compact = false,
}: {
  icon?: ReactNode;
  eyebrow?: string;
  title: string;
  body?: string;
  action?: ReactNode;
  compact?: boolean;
}) {
  return (
    <div className={`glass-quiet flex flex-col items-center justify-center rounded-[var(--r-lg)] text-center ${compact ? "px-6 py-8" : "px-8 py-14"}`}>
      {icon && (
        <span className="mb-4 grid h-11 w-11 place-items-center rounded-[var(--r-sm)] border border-[var(--border-1)] bg-[var(--surface-1)] text-[var(--text-3)]">
          {icon}
        </span>
      )}
      {eyebrow && <div className="eyebrow mb-2">{eyebrow}</div>}
      <h3 className="t-title">{title}</h3>
      {body && <p className="t-meta mt-2 max-w-sm leading-relaxed">{body}</p>}
      {action && <div className="mt-5 flex items-center gap-2">{action}</div>}
    </div>
  );
}

export function ErrorState({ title = "Connection issue", body, onRetry, retrying = false }: { title?: string; body?: string; onRetry?: () => void; retrying?: boolean }) {
  return (
    <div className="glass-quiet flex items-start gap-3.5 rounded-[var(--r-lg)] px-5 py-4">
      <span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-[var(--r-xs)] border border-[rgba(255,110,110,0.25)] bg-[rgba(255,110,110,0.08)] text-[#ff9b9b]">
        <IconWarn size={15} />
      </span>
      <div className="min-w-0 flex-1">
        <div className="text-[13.5px] font-medium text-[var(--text-1)]">{title}</div>
        {body && <div className="t-meta mt-1 leading-relaxed">{body}</div>}
      </div>
      {onRetry && (
        <button className="btn btn-glass btn-sm shrink-0" onClick={onRetry} disabled={retrying}>
          <IconRefresh size={13} className={retrying ? "animate-spin" : ""} />
          Retry
        </button>
      )}
    </div>
  );
}

/* ============================== loading ================================= */

export function Skeleton({ className = "", style }: { className?: string; style?: CSSProperties }) {
  return <div className={`skeleton ${className}`} style={style} />;
}

export function CardSkeleton({ width = "w-[300px]", height = "h-[168px]" }: { width?: string; height?: string }) {
  return (
    <div className={`glass-quiet ${width} ${height} shrink-0 rounded-[var(--r-lg)] p-5`}>
      <Skeleton className="h-3 w-20" />
      <Skeleton className="mt-4 h-4 w-3/4" />
      <Skeleton className="mt-2.5 h-3 w-full" />
      <Skeleton className="mt-2 h-3 w-2/3" />
    </div>
  );
}

export function PanelSkeleton({ lines = 4 }: { lines?: number }) {
  return (
    <div className="glass panel">
      <Skeleton className="h-3 w-24" />
      <Skeleton className="mt-5 h-8 w-40" />
      <div className="mt-6 space-y-3">
        {Array.from({ length: lines }).map((_, i) => (
          <Skeleton key={i} className="h-3.5" style={{ width: `${92 - i * 9}%` }} />
        ))}
      </div>
    </div>
  );
}
